#!/usr/bin/env bash

while IFS= read -r line; do

    count=$(grep -ic "$line" have-installers.txt)

    if [[ $count -gt 0 ]]; then
        echo "found installers for $line..."
        grep -i "$line" have-installers.txt
    fi

done < manual-to-cask.txt

# found installers for adium...
# Adium_1.5.10.1.dmg
# Radium-2.8.4.dmg
# found installers for app-cleaner...
# app-cleaner-uninstaller.dmg
# found installers for archiver...
# Archiver.zip
# Archiver2.7z
# Archiver3.zip
# found installers for avitools...
# avitools3.2.3.7z
# avitools3.4.3.zip
# avitools3.6.4.zip
# avitools3.6.6.zip
# avitools3.7.1.zip
# avitools3.7.2.zip
# found installers for backuploupe...
# BackupLoupe_2.4.1.tar.bz2
# found installers for bettertouchtool...
# BetterTouchTool.zip
# found installers for cardhop...
# Cardhop_1.0.7.zip
# found installers for chicken...
# Chicken-2.2b2.dmg
# found installers for cronnix...
# CronniX_3.0.2.app.zip
# found installers for daisydisk...
# DaisyDisk.dmg
# DaisyDisk.zip
# found installers for discord...
# Discord.dmg
# found installers for divvy...
# Divvy.zip
# found installers for etrecheckpro...
# EtreCheckPro 2.zip
# EtreCheckPro.zip
# found installers for farrago...
# Farrago.zip
# found installers for filebot...
# FileBot_4.8.2.pkg
# FileBot_4.8.5.pkg
# found installers for fission...
# Fission.7z
# found installers for flux...
# Flux.zip
# Flux36-3.zip
# found installers for franz...
# Franz-5.1.0.dmg
# franz-5.0.0-beta.18.dmg
# found installers for geektool...
# GeekTool-3.1.1-311.zip
# found installers for grandperspective...
# GrandPerspective-0_9_13_1.dmg
# GrandPerspective-1_8_1.dmg
# GrandPerspective-2_0_0.dmg
# found installers for hammerspoon...
# Hammerspoon-0.9.56.zip
# Hammerspoon-0.9.75.zip
# found installers for handbrake...
# HandBrake-0.10.0-MacOSX.6_CLI_x86_64.dmg
# HandBrake-1.2.2.dmg
# HandBrake-1.3.1.zip
# HandBrakeCLI-1.3.1.dmg
# found installers for iconizer...
# Iconizer.dmg
# found installers for iexplorer...
# iExplorer-3.1.dmg
# iExplorer-4.0.10.0.dmg
# found installers for imagealpha...
# ImageAlpha.app.7z
# ImageAlpha.zip
# ImageAlpha1.3.0.7.tar.bz2
# found installers for kaleidoscope...
# James Stout.KaleidoscopeLicense
# Kaleidoscope-2.0.0-84.7z
# Kaleidoscope-2.2.0-439.zip
# Kaleidoscope-2.2.2-1376.zip
# Kaleidoscope1.zip
# found installers for keybase...
# Keybase.dmg
# found installers for launchcontrol...
# LaunchControl_1.1.1.7z
# found installers for makemkv...
# makemkv_v1.10.10_osx.dmg
# makemkv_v1.12.2_osx.dmg
# makemkv_v1.12.3_osx.dmg
# found installers for marsedit...
# MarsEdit3.5.6.zip
# found installers for mkvtools...
# mkvtools3.6.4.zip
# mkvtools3.6.6.zip
# mkvtools3.7.1.zip
# mkvtools3.7.2.zip
# found installers for mp4tools...
# mp4tools3.6.4.zip
# mp4tools3.6.7.zip
# mp4tools3.7.1.zip
# mp4tools3.7.2.zip
# found installers for mycrypto...
# mac_1.7.7_MyCrypto.dmg
# found installers for namebench...
# namebench-1.3.1-Mac_OS_X.dmg
# namebench-1.3.1-source.tgz
# namebench-1.3.1.zip
# namebench-source-archive.zip
# found installers for netspot...
# NetSpot.dmg
# found installers for nvalt...
# nvalt2.2b94.zip
# found installers for onyx...
# OnyX 2.dmg
# OnyX.dmg
# found installers for pacifist...
# Pacifist_3.0.10 2.7z
# found installers for pdfpen...
# PDFpen.7z
# PDFpen.dmg
# PDFpen.zip
# found installers for photosync...
# photosync_4_0.dmg
# found installers for postico...
# postico-1.5.10.zip
# postico-1.5.12.zip
# postico-1.5.13.zip
# found installers for sherlock...
# Sherlock-1.7.5.dmg
# Sherlock.dmg
# found installers for simpholders...
# simpholders-3_0_5.dmg
# simpholders_2_2.dmg
# simpholders_3.0.b3.dmg
# found installers for sizeup...
# SizeUp 2.zip
# SizeUp.zip
# found installers for skype...
# Skype-8.51.0.72.dmg
# found installers for smcfancontrol...
# smcfancontrol_2_4.zip
# found installers for soundsource...
# SoundSource.zip
# SoundSource4.zip
# SoundSource_07_19_2125.zip
# found installers for subtools...
# subtools1.0.b2.7z
# found installers for superduper...
# SuperDuper!.dmg
# found installers for teacode...
# TeaCode-1.0.zip
# found installers for textexpander...
# TextExpander.zip
# TextExpander_6.2.2.1.zip
# found installers for textmate...
# TextMate_2.0-beta.7.4.tbz
# TextMate_2.0-rc.9.tbz
# found installers for transmission...
# Transmission-2.73.dmg
# Transmission-2.93.dmg
# Transmission-2.94.dmg
# Transmission.7z
# found installers for vanilla...
# Vanilla.dmg
# found installers for versions...
# Versions-1.3-1052.zip
# Versions1.2.7z
# found installers for xld...
# xld-20130407.dmg
# found installers for yojimbo...
# Yojimbo_4.0.1.dmg
# Yojimbo_4.1.4.dmg
# yojimbo-304.dmg